
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_DB_PORT") { '5432' } %>
  username: <%= ENV.fetch("MANUF_DB_USER_DEV") { 'postgres' } %>
  password: <%= ENV.fetch("MANUF_DB_PASSWORD_DEV") { '' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 16 } %>
  checkout_timeout: <%= ENV.fetch('CHECKOUT_TIMEOUT') { 5 }%>

development:
  <<: *default
  database: manufacturing_development

test:
  <<: *default
  database: manufacturing_test

production:
  <<: *default
  database: <%= ENV.fetch("MANUF_DB") {''} %>
  username: <%= ENV.fetch("MANUF_DB_USER") {''} %>
  password: <%= ENV.fetch("MANUF_DB_PASSWORD") {''} %>
