
default: &default
  username: <%= ENV['MANUF_DB_USER_DEV'] %>
  password: <%= ENV['MANUF_DB_PASSWORD_DEV'] %>
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 16
  host: <%= ENV.fetch("POSTGRES_DB_HOST", 'localhost') %>
  port: <%= ENV.fetch("POSTGRES_DB_PORT", 5432) %>
  timeout: 5000
  checkout_timeout: <%= ENV["CHECKOUT_TIMEOUT"].to_i %>

development:
  <<: *default
  database: manufacturing_development

test:
  <<: *default
  database: manufacturing_test

production:
  <<: *default
  database: <%= ENV['MANUF_DB'] %>
  username: <%= ENV['MANUF_DB_USER'] %>
  password: <%= ENV['MANUF_DB_PASSWORD'] %>
